apiVersion: apps/v1
kind: Deployment
metadata:
  name: fschallengeapp
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fschallengeapp
  template:
    metadata:
      labels:
        app: fschallengeapp
    spec:
      containers:
        - name: fscontainer
          image: ghcr.io/daniel55247/try2/imagefstry2:latest
          ports:
            - containerPort: 8080
          command: [ "nginx", "-g", "daemon off;"]