# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: FSLab Test AWS CI/CD

on:
  push:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 15
        cache: 'npm'
        cache-dependency-path: codebase/rdicir-0.1.0/package-lock.json
    
    - name: Execute code
      working-directory: codebase/rdicidr-0.1.0
      run: npm install
    - run: npm run lint
    - run: npm run prettier
    - run: CI=true npm run test
    - run: npm run build --if-present
